### ISSUE TITLE
Go through site readiness checklist. 

### ISSUE THREAD

**Issue by catheraaine** [sparkbox/local-events-project#160]
# Site Completeness Checklist
This list uses [Github Checklists](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments)

---

## Early Dev Checklist

* [x] Dev site disallows indexing
* [x] Other item
* [ ] all states of navigation/buttons (active, hover, inactive, etc)
* [x] dropdown menus
* [x] pagination
* [x] headline styles that work when very long (wrap to multiple lines)
* [x] Purchase CMS license (if applicable)

### Design

* [x] Hi-Res (retina-ready) images for any images that are vector/text
based
* [x] favicon.ico - use [favicon generator](http://realfavicongenerator.net), seriously.

### Content

* [x] 404 page
* [x] search results page
* [x] copyright page
* [ ] terms of use page
* [ ] any other legal page
* [ ] credit page / sparkbox link
* [x] humans.txt included
* [x] robots.txt file pointing to sitemap.xml
* [x] sitemap.xml
* [x] meta tags (description)
* [x] page titles appropriate and SEO
* [x] imgs with alt text
* [x] img title attributes appropriate and SEO

### Markup/CSS/JS Related

(in dynamic content)
* [x] basic link styles
* [x] blockquotes
* [x] unordered lists
* [x] ordered lists
* [x] all 6 header tags
* [x] inline images (left, right, center, etc in CMS content)
* [x] print stylesheet
* [ ] jump to content link near top of markup (for accessibility)
* [x] check for empty (href=#) links
* [ ] dynamically generated copyright date
* [x] form validation in place
* [x] error styles
* [x] form required fields tested
* [x] forms submit properly
* [ ] HTML validated
* [ ] CSS validated
* [x] No JS errors
* [x] CSS in the header
* [x] JS in the footer
* [x] Run Through [a11yproject](http://a11yproject.com/checklist.html) accessibility checklist

### Testing

Desktop
* [ ] are we going to have compatibility mode issues in IE?
* [ ] content accessible in IE 7,8,9
* [ ] design/content right in IE 9/10
* [ ] design/content right in latest PC Chrome
* [ ] design/content right in latest PC FireFox
* [ ] design/content right in latest Mac Safari
* [ ] design/content right in latest Mac Chrome
* [ ] design/content right in latest Mac FireFox
* [ ] design right on a retina display

Devices
* [ ] design/content right in iOS phone
* [ ] design/content right in iOS tablet
* [ ] design/content right in Android phone
* [ ] design/content right in Android tablet
* [ ] design/content right in Blackberry phone
* [ ] design/content right in Blackberry tablet
* [ ] design/content right in Kindle tablet
* [ ] design/content right in Windows phone
* [ ] design/content right in Windows tablet

###  Plan Launch

* [x] Determine hosting solution.
* [x] Determine launch plan. (staging environment, DNS changeover, etc)
* [x] Get client’s google tracking ID.
* [x] Get client’s mail marketing (mailchimp) ID.
* [ ] Get client’s social share ID’s.
* [ ] Get client’s social pages.

---

## Launch Checklist

* [ ] allow indexing
* [ ] Markup/CSS/JS Related
* [ ] include google analytics (proper UA string)
* [ ] Un-Comment-Out the Google Analytics ID so it works post launch.
* [ ] ensure local jquery files are in place
* [ ] local jquery version should be same as google jquery version
* [ ] add selectivizr only if needed
* [ ] add modernizr only if needed
* [ ] build custom version of modernizr (keep file small)

### Server Related

* [x] The site is backed up
* [x] Using expires headers
* [x] Using gzip
* [x] Minifying and combining our CSS
* [x] Include caching option
* [ ] Page weight has been tested and is acceptable.

### Project Management Related

After we launch a site, this is the procedure that we will follow. We
will wait approximately 14 days to allow for last minute changes,
bugs, etc.

* [ ] send thank you note after final payment is received and remind of
    30-day support timeframe
* [ ] Send documentation to client. (Check that code is commented well,
    send plugin list, any live or documented training)
* [ ] Archive live code. (Repository or Basecamp.)

### Marketing

* [ ] Submit to Galleries
* [ ] Add to seesparkbox.com work section
* [ ] Blog about launch
* [ ] Tweet from @hearsparkbox
* [ ] Request client quote/recommendation (if appropriate).

### Gallery Submittal:

1. [ ] We do a “normal submission” on www.awwwards.com because
it is well respected and well screened
http://www.awwwards.com/submit
for around $21

2. [ ] Then we use http://thecssgallerylist.com/ for sheer volume to
submit to 100 other sites (hitting many popular ones) for $20.

3. [ ] Then we hand-submit the site to a few other purposeful (but free)
galleries such as:
mediaqueri.es
http://www.mobileawesomeness.com/
http://creattica.com/
